/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current environment state */
        get: operations["getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get branches for all environments */
        get: operations["getBranches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CommitInfo: {
            /** @description Full commit SHA */
            hexsha: string;
            /** @description Commit author name */
            author: string;
            /** @description Commit message */
            message: string;
        };
        /** @description Tuple of [branchName, commitHash] */
        BranchCommitPair: string[];
        PipelineStep: {
            /** @description Step name */
            name: string;
            /** @description Step status (any shape) */
            status: unknown;
            /** @description Whether this step has an error */
            error?: boolean;
        };
        EnvironmentDto: {
            /** @description Environment identifier */
            id: string;
            /** @description Array of [branchName, commitHash] pairs */
            branches: components["schemas"]["BranchCommitPair"][];
            /** @description Whether this is a dry-run environment */
            dry: boolean;
            /** @description Repository path or URL */
            repo: string;
            /** @description Pipeline steps with their statuses */
            pipeline: components["schemas"]["PipelineStep"][];
        };
        WsIncomingMessage: {
            branches?: components["schemas"]["BranchesData"];
            environments?: components["schemas"]["EnvironmentsData"];
            error?: {
                message?: string;
            };
        };
        WsUpdatePayload: {
            /** @description Environment ID (empty string to trigger refresh) */
            id: string;
            branches?: components["schemas"]["BranchCommitPair"][];
        };
        WsOutgoingMessage: {
            update: components["schemas"]["WsUpdatePayload"];
        };
        /** @description Dict[envId, Dict[branchName, CommitInfo[]]] */
        BranchesData: {
            [key: string]: {
                [key: string]: components["schemas"]["CommitInfo"][];
            };
        };
        /** @description Dict[envId, EnvironmentDto] */
        EnvironmentsData: {
            [key: string]: components["schemas"]["EnvironmentDto"];
        };
        StateResponse: components["schemas"]["EnvironmentsData"];
        BranchesResponse: components["schemas"]["BranchesData"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current state of all environments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
        };
    };
    getBranches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branches grouped by environment and branch name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchesResponse"];
                };
            };
        };
    };
}
